apiVersion: v1
kind: Namespace
metadata:
  name: trisotech-dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: trisotech-dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: nginx
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
